<?php
$magentoPoints = 0;
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $readConnection = Mage::getSingleton('core/resource')->getConnection('core_read');    
    $sql = "SELECT * FROM rewards_customer_index_points WHERE customer_id = ".$customer->getId();
    $rows = $readConnection->fetchAll($sql);    
    if(isset($rows[0]['customer_points_usable'])){
        $magentoPoints = $rows[0]['customer_points_usable'];
    }
}
?>
<?php if($magentoPoints >= 100): ?>


<?php $rewards = $this->getDistriRewards(); ?>
<div class="rewards-product-view-points"> 
    <script type="text/javascript">
    // optionsPrice.productOldPrice = optionsPrice.productPrice;
    <?php if($this->printOptionsPrice()): ?>
        // If we're running Magento 1.4 and the product is simple, we need refactor the JSON config.
        optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    <?php endif; ?>
    </script>
    <?php if($this->doShowRedeemer() || sizeof($rewards) > 0): ?>
    <div class="product-view-points" id="product-view-points">
        <?php if($this->doShowRedeemer()): ?>
            <?php if(!$this->getProduct()->isGrouped()): /* Grouped products don't show the catalog redemption selector*/  ?>
                <?php echo $this->getRedeemedHtml(); ?>
            <?php endif; ?>
        <?php endif; ?>
        <div id="points-total">
            <?php if(sizeof($rewards) > 0): ?>
               <?php echo $this->getEarnedHtml(); ?>
            <?php endif; ?>
        </div>
    </div>
    <div class="divider"></div>
    <?php endif; ?>
    
    <?php if ($this->getProduct()->isGrouped() ):?>
    <?php
    $url = $this->getUrl('rewards/product_view_distribution/updatePoints', array('_secure' => false));
    if (Mage::app()->getStore()->isCurrentlySecure()) {
        $url = $this->getUrl('rewards/product_view_distribution/updatePoints', array('_secure' => true));
    }
    ?>
    <script type="text/javascript">
        var elems = $$("table#super-product-table tbody tr td input.qty");
        elems.each(function(item){
            Event.observe(item, 'change', function(){
                var param = {};
                elems.each(function(i){
                    key = i.name.slice(12,-1);
                    param[key] =  parseInt(i.value);
                });
                param["product_id"] = <?php echo $this->getProduct()->getId();?>;
                new Ajax.Updater("points-total",'<?php echo $url; ?>',{
                    method:'post',
                    parameters: param
                },{asynchronous:false});
            });
        });
    </script>
    <?php endif;?>
    
    <?php if (sizeof($this->getProduct()->getTierPrice())) : ?>
    <script type="text/javascript">
    document.observe("dom:loaded", function() {
        var elems = $$("div.add-to-cart input.qty");
        elems.each(function(item){
            Event.observe(item, 'change', function(){
                var param = {};
                var tierprices = <?php echo json_encode($this->getProduct()->getTierPrice());?>;
                var group_id = <?php echo Mage::getSingleton('customer/session')->getCustomerGroupId();?>;
                param["product_id"] = <?php echo $this->getProduct()->getId();?>;
                param["qty"] = item.value;
                for (var key in tierprices) {
                    if (tierprices.hasOwnProperty(key)) {
                        obj = tierprices[key];
                    }
                    if (!(obj.all_groups === "1")) {
                        if (!(obj.cust_group === group_id)){
                            return;
                        }
                    }
                    if (obj.price_qty <= parseInt(param["qty"])) {
                        // make sure it's a number
                        optionsPrice.productPriceBeforeRedemptions = +obj.website_price;
                    }
                }
                syncWithCustomOptions();
            });
        });
    });
    </script>
    <?php endif;?>
    <script type="text/javascript">
    <?php if( Mage::helper("rewards/version")->isEnterpriseAtLeast("1.11.2.0")):?>
        document.observe("dom:loaded", function() {
              if($('bundleSummary') != undefined) {
                   if($('bundleSummary').getElementsBySelector('.add-to-cart').first() != undefined ) {
                        $('bundleSummary').getElementsBySelector('.add-to-cart').first().insert({after: $('product-view-points')});
                   } else if($('bundleSummary').getElementsBySelector('.price-box').first() != undefined) {
                        $('bundleSummary').getElementsBySelector('.price-box').first().insert({after: $('product-view-points')});
                   }
               }
        });
    <?php endif;?>
    
    </script>
</div>

<?php endif; ?>