<?php
$helper				= Mage::helper('lightboxes');
$rel                = $helper->getLightboxRel($helper->getConfig('lightbox_type'));
$class              = $helper->getLightboxClass($helper->getConfig('lightbox_type'));
$mainImageSize      = $helper->getMainImageSize();
$popUpImageSize     = $helper->getPopupImageSize();
$thumbnailSize      = $helper->getThumbnailImageSize();
$includeMainImage	= $helper->getConfig('include_mainimage_in_lightbox');

$mainImageRel		= $rel;
$mainImageClass		= $class;
if($helper->getConfig('lightbox_type') == 'piroboxextended' && !$includeMainImage){
	$mainImageRel	= 'single';
	$mainImageClass = 'pirobox';
}elseif($helper->getConfig('lightbox_type') == 'prettyphoto' && !$includeMainImage){
	$mainImageRel	= 'prettyPhoto';
	$mainImageClass = '';
}elseif(!in_array($helper->getConfig('lightbox_type'),array('piroboxextended', 'prettyphoto')) && !$includeMainImage){
	$mainImageRel	= $rel . '-main';
	$mainImageClass = $class . '-main';
}
?>
<!-- jQuery LightBoxes -->
    <?php if($helper->getConfig('include_jquery', 'lightboxes_confliction') && $helper->getConfig('include_jquery_in', 'lightboxes_confliction') == 'media'): 	?>
		<?php echo $this->getChildHtml('jquery_inclusion'); ?>
	<?php endif; ?>

    <?php if($helper->getConfig('include_lighboxes_in', 'lightboxes_confliction') == 'media'): ?>
		<?php echo $this->getChildHtml('lightboxes_inclusion'); ?>
	<?php endif; ?>

	<?php if($helper->getConfig('include_initialization_in', 'lightboxes_confliction') == 'media'): ?>
		<?php echo $this->getChildHtml('lightboxes_initialization'); ?>
	<?php endif; ?>
<!-- //jQuery LightBoxes -->
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>

<?php
//check if zoomer is disabled
if($helper->getConfig('disable_zoombar')):
?>
<p class="product-image">
    <?php
       /* $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($mainImageSize[0], $mainImageSize[1]).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';*/

       $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';


        if(empty($popUpImageSize[0]) || empty($popUpImageSize[0])):
            $popUpImage = $this->helper('catalog/image')->init($_product, 'image');
        else:
            $popUpImage = $this->helper('catalog/image')->init($_product, 'image')->resize($popUpImageSize[0], $popUpImageSize[1]);
        endif;

    ?>
    <a href="<?php echo $popUpImage; ?>" rel="<?php echo $mainImageRel; ?>" class="<?php echo $mainImageClass; ?>" title="<?php echo $this->htmlEscape($this->getImageLabel()) ?>"><?php echo $_helper->productAttribute($_product, $_img, 'image'); ?></a>
</p>
<?php else: ?>
<p class="product-image product-image-zoom">
    <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
<div class="zoom">
    <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
    <div id="track">
        <div id="handle"></div>
    </div>
    <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
</div>
<script type="text/javascript">
//<![CDATA[
    Event.observe(window, 'load', function() {
        product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
    });
//]]>
</script>
<?php endif; ?>

<?php else: ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>
<?php if (count($this->getGalleryImages()) > 0):
?>
<div class="more-views">
    <?php /*?><h2><?php echo $helper->getConfig('more_views_label') ?></h2><?php */?>
    <ul class="prdsmollim">
    <?php foreach ($this->getGalleryImages() as $_image):
            if(empty($popUpImageSize[0]) || empty($popUpImageSize[0])):
                $popUpImage = $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile());
            else:
                $popUpImage = $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize();
            endif;
    ?>
        <li>
            <?php /* <a href="<?php echo $popUpImage; ?>" rel="<?php echo $rel; ?>" class="<?php echo $class; ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($thumbnailSize[0], $thumbnailSize[1]); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /> */ ?>
            <a href="<?php echo $popUpImage; ?>" rel="<?php echo $rel; ?>" class="<?php echo $class; ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(90, 90); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
            </a>

        </li>

    <?php endforeach; ?>

        <?php $_description = $this->getProduct()->getAttVideo(); ?>
        <?php $baseurl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>

        <?php if ($_description): ?>
        <?php 
            // $videoid= $_product->getResource()->getAttribute('att_video')->getFrontend()->getValue($_product);
            // $video_thumb = '';
            // if($_product->getResource()->getAttribute('att_video_thumb')->getFrontend()->getValue($_product)){
            //     $video_thumb= $_product->getResource()->getAttribute('att_video_thumb')->getFrontend()->getValue($_product);
            // }
           
        ?> 
        <?php /*
        <li>
        <a class="video-fancy" href="<?php echo $videoid; ?>" >
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$video_thumb;?>" width="106" height="106">
            <span><img src="<?php echo $this->getSkinUrl('images/play-video.png');?>"></span>
        </a> 
        </li>
        */ ?>


        <!-- insert fancybox script-->
        <script type="text/javascript">// <![CDATA[
        jQuery(document).ready(function() {  
          jQuery(".video-fancy").click(function() {
              jQuery.fancybox({
                    'padding'       : 0,
                    'autoScale'     : false,
                    'transitionIn'  : 'none',
                    'transitionOut' : 'none',
                    'title'         : this.title,
                    'width'         : 640,
                    'height'        : 385,
                    'href'          : this.href.replace(new RegExp("watch\\?v=", "i"), 'v/'),
                    'type'          : 'swf',
                    'swf'           : {
                    'wmode'             : 'transparent',
                    'allowfullscreen'   : 'true'
                  }
              });

            return false;
          });
        });
        // ]]></script>
        <?php endif; ?>
        
    </ul>
</div>
<?php endif; ?>