
<?php if($this->showPreferences()): ?>
<!-- BEGIN referral preferences fieldset -->
<form action="<?php echo $this->getUrl('rewardsref/customer/savePref/') ?>" method="post" id="form-validate">
<div class="box-account my_referrals-urlcode_group">
    <div class="box-head tpspbrdnon">
    	<h2 class="ourhd-summary"><?php echo $this->__('Referral Preferences'); ?></h2>
    </div>
    <ul class="referral-preference">
        <li>
            <div class="urlcode-checkbox">
                <input type="checkbox" name="rewardsref_notify_on_referral" 
                        <?php if($this->getCustomer()->getRewardsrefNotifyOnReferral()): ?>checked="checked" <?php endif; ?>
                        value="1" 
                        title="<?php echo $this->__('Notify me when I earn points from my referral') ?>" 
                        class="checkbox" id="rewardsref_notify_on_referral" />
                <label for="rewardsref_notify_on_referral"><?php echo $this->__('Notify me when I earn points from my referral') ?></label>
            </div>
        </li>
    </ul>
    <div class="button-set fullrowidth" style="margin-top:0px">
    	<button type="submit" title="<?php echo $this->__('Save Preferences') ?>" class="button savebtnnew btnsumsendgrd">
    		<span><span><?php echo $this->__('Save Preferences') ?></span></span>
    	</button>
    </div>
</div>
</form>
<!-- END referral preferences fieldset -->

<?php endif ?>