<?php $ControllerName = $this->getRequest()->getControllerName(); ?>

<!-- customer/product -->
<?php if($ControllerName == 'customer') : ?>

<div class="<?php echo $this->getWidgetClass(); ?> rewardssocialicondiv" >
    <?php foreach ($this->getSortedChildren() as $name): ?>
        <?php $block = $this->getLayout()->getBlock($name); ?>
        <?php if (!$block): ?>
            <?php Mage::throwException(Mage::helper('core')->__('Invalid block: %s', $name)); ?>
        <?php endif; ?>
        <?php if ($this->getProduct()) : ?>
            <?php $block->setProduct($this->getProduct()); ?>
        <?php endif; ?>
        <?php if ($this->getOrderId()) : ?>
            <?php $block->setOrderId($this->getOrderId()); ?>
        <?php endif; ?>

        <?php if (!$block->getIsHidden()) : ?>
            <?php echo $block->toHtml(); ?>
        <?php endif; ?>
    <?php endforeach ?>

    <div class="socrowfull">
        <?php echo $this->getPointsNotificationBlock()->toHtml(); ?>
    </div>
    
</div>
<?php endif ?>