<?php 
    $sku          = 'tripack'; 
    $_product     = Mage::getModel('catalog/product')->loadByAttribute('sku', $sku);
    $iProductID   = $_product->getID();
    $url = Mage::helper('checkout/cart')->getAddUrl($_product);

    $selectionCollection = $_product->getTypeInstance(true)->getSelectionsCollection(
		$_product->getTypeInstance(true)->getOptionsIds($_product), $_product
	);
?>

<form  action="<?php echo $url; ?>" id="product_addtocart_form" method="post">
    <?php foreach($selectionCollection as $option) : ?>
		<input type="hidden" name="bundle_option[<?php echo $option->getOptionId(); ?>]" value="<?php echo $option->getSelectionId();?>" />
	<?php endforeach; ?>
    <input type="hidden" name="qty" id="form_quantity" value="1" />
    <input type="hidden" name="product" id="" value="<?php echo $iProductID; ?>" />
</form>

<script type="text/javascript">
var productAddToCartForm = new VarienForm('product_addtocart_form');
productAddToCartForm.submit = function(button, url) {
    if (this.validator.validate()) {
        var form = this.form;
        var oldUrl = form.action;

        if (url) {
           form.action = url;
        }
        var e = null;
        try {
            this.form.submit();
        } catch (e) {
        }
        this.form.action = oldUrl;
        if (e) {
            throw e;
        }

        if (button && button != 'undefined') {
            button.disabled = true;
        }
    }
}.bind(productAddToCartForm);

productAddToCartForm.submitLight = function(button, url){
    if(this.validator) {
        var nv = Validation.methods;
        delete Validation.methods['required-entry'];
        delete Validation.methods['validate-one-required'];
        delete Validation.methods['validate-one-required-by-name'];
        // Remove custom datetime validators
        for (var methodName in Validation.methods) {
            if (methodName.match(/^validate-datetime-.*/i)) {
                delete Validation.methods[methodName];
            }
        }

        if (this.validator.validate()) {
            if (url) {
                this.form.action = url;
            }
            this.form.submit();
        }
        Object.extend(Validation.methods, nv);
    }
}.bind(productAddToCartForm);

function add_to_cart(ele){
	productAddToCartForm.submit(ele);
	return false;
}
</script>